//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func validate() throws {

  }


  /// This `_R.color` struct is generated, and contains static references to 11 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `evenColor`.
    var evenColor: RswiftResources.ColorResource { .init(name: "evenColor", path: [], bundle: bundle) }

    /// Color `fixedColor`.
    var fixedColor: RswiftResources.ColorResource { .init(name: "fixedColor", path: [], bundle: bundle) }

    /// Color `oddColor`.
    var oddColor: RswiftResources.ColorResource { .init(name: "oddColor", path: [], bundle: bundle) }

    /// Color `rewriteButtonColor`.
    var rewriteButtonColor: RswiftResources.ColorResource { .init(name: "rewriteButtonColor", path: [], bundle: bundle) }

    /// Color `rewriteLightColor`.
    var rewriteLightColor: RswiftResources.ColorResource { .init(name: "rewriteLightColor", path: [], bundle: bundle) }

    /// Color `rewriteShadowColor`.
    var rewriteShadowColor: RswiftResources.ColorResource { .init(name: "rewriteShadowColor", path: [], bundle: bundle) }

    /// Color `scoreColor`.
    var scoreColor: RswiftResources.ColorResource { .init(name: "scoreColor", path: [], bundle: bundle) }

    /// Color `selectButtonColor`.
    var selectButtonColor: RswiftResources.ColorResource { .init(name: "selectButtonColor", path: [], bundle: bundle) }

    /// Color `selectLightColor`.
    var selectLightColor: RswiftResources.ColorResource { .init(name: "selectLightColor", path: [], bundle: bundle) }

    /// Color `selectShadowColor`.
    var selectShadowColor: RswiftResources.ColorResource { .init(name: "selectShadowColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 1 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `icon`.
    var icon: RswiftResources.ImageResource { .init(name: "icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }
}